#!/bin/bash

# Results directory
resdir="scan-results"

# Prompt user for target IP address and ports
echo "Enter target's address [0.0.0.0]:"
read -r target_ip

# Set default value for target IP if not provided
if [ -z "$target_ip" ]; then
  target_ip="0.0.0.0"
fi

echo "Specify target's ports [def=all; 21,80,443...]:"
read -r specified_ports

# Set default value for ports if not provided
if [ -z "$specified_ports" ]; then
  echo "Scanning on ALL ports"
  specified_ports="0-65535"
else
  echo "Scanning on $specified_ports ports"
fi

# Make directory for scanning results if it doesn't already exist
if [ ! -d "$resdir" ]; then
  mkdir "$resdir"
fi

if [ ! -d "$resdir/$target_ip" ]; then
  mkdir "$resdir/$target_ip"
fi

# Scan for open ports
open_ports=$(nmap -p"$specified_ports" --min-rate=1000 "$target_ip" -T4 | grep "^[0-9]" | cut -d '/' -f 1 | tr '\n' ',' | sed s/,$//)

# Count open ports
open_ports_array=($(echo "$open_ports" | tr ',' '\n'))
counter=${#open_ports_array[@]}
echo "Found $counter open ports: $open_ports"

# Export ports to TXT
echo "$open_ports" > "$resdir/$target_ip/ports.txt"

# Prompt user for arguments for nmap scan
echo "Specify arguments for nmap scanning [-Pn, -A, -sC, -sV...]:"
read -ra args

# Scan ports using nmap
echo "Performing scanning on these ports with arguments ${args[*]}:"
nmap -p"$specified_ports" "${args[@]}" "$target_ip" -oX "$resdir/$target_ip/scan.xml" -o "$resdir/$target_ip/scan.txt"
# Convert xml scan results to csv
echo "Converting to .csv..."
nmap_xml_parser.py -f "$resdir/$target_ip/scan.xml" -csv "$resdir/$target_ip/scan.csv" | grep '^\['

# Output
echo "Done! Check $resdir folder"
echo "Ports are available at: TXT: $resdir/$target_ip/ports.txt"