#!/bin/zsh

# Results directory
resdir="scan-results"
# Warning
echo "\t\t\n[\e[4;31mWARNING\e[0m]"
echo "\e[1;31mDirectory named $resdir will be generated\e[0m\n\n"

# Assigning victim's host address
echo "Enter \e[31mtarget's\e[0m address \e[1;34m[0.0.0.0]\e[0m"
read -r target_ip
# Default value
if [ -z "$target_ip" ]; then
        target_ip="0.0.0.0"
fi

echo "Specify \e[31mtarget's\e[0m ports \e[1;34m[def=all; 21,80,443...]\e[0m"

# Ports assignment
read -r specified_ports
# Default value
if [ -z "$specified_ports" ]; then
        echo "scanning on \e[32mALL\e[0m ports"
        specified_ports="0-65535"
else
        echo "scanning on \e[32m$specified_ports\e[0m ports"
fi

# Making a directory for scanning results
if [ ! -d $resdir ]; then
        mkdir $resdir
fi
if [ ! -d $resdir/$target_ip ]; then
        mkdir $resdir/$target_ip
fi

# Scanning for open ports
ports=$(nmap -p$specified_ports --min-rate=1000 $target_ip -T4  | grep "^[0-9]" | cut -d '/' -f 1 | tr '\n'  ',' | sed s/,$//)
# Count open ports
portsIN=($(echo $ports | tr ',' "\n"))
counter=${#portsIN[@]}
counter=($counter)
echo "Found $counter open ports: \e[32m$ports\e[0m"

# Export ports to TXT
touch $resdir/ports.txt | echo "$ports" >  $resdir/$target_ip/ports.txt

# Arguments for nmap
printf "\nSpecify arguments for nmap scanning \e[1;34m[-Pn, -A, -sC, -sV...]\e[0m\n"
read -r args
# Nmap scanning
echo "\e[1;33mPerforming scanning on these ports with arguments $args :\e[0m "
nmap -p"$specified_ports" "$args" "$target_ip" -oX  $resdir/"$target_ip"/scan.xml -o $resdir/"$target_ip"/scan.txt

# Convert xml scan results to csv
printf "\n\e[1;33mConverting to .csv...\e[0m\n"
nmap_xml_parser.py -f $resdir/$target_ip/scan.xml -csv $resdir/$target_ip/scan.csv | grep '^\['

# Output
printf "\e[32m\nDone! Check $resdir folder\e[0m\n"
printf "Ports are availiable at:\e[1;34m\nTXT:\e[0m\e[34m\t%s/ports.txt\e[0m\n" "$resdir/$target_ip"
printf "Scan results are availiable at:\n"
printf "\e[1;34mXML:\e[0m\e[34m\t%s/scan.xmll\e[0m\n" "$resdir/$target_ip"
printf "\e[1;34mCSV:\e[0m\e[34m\t%s/scan.csv\e[0m\n" "$resdir/$target_ip"
printf "\e[1;34mTXT:\e[0m\e[34m\t%s/scan.txt\e[0m\n" "$resdir/$target_ip"
